### ISSUE TITLE
Take a look at the new "tutorial" section of the wiki

### ISSUE THREAD

**Issue by rmera** [Martini-Force-Field-Initiative/Bartender#10]
Hey!

I just added this section to the wiki:

https://github.com/Martini-Force-Field-Initiative/Bartender/wiki/example

When you can, please take a look. 

Cheers!

**Comment by GilbertoPPereira** [comment]
I looked at it and it looks ok. 
I think we could have a couple more figures, especially one which shows the "bead sharing" part which is noted during the tutorial and one that shows the mapping. I can provide you this figure, or we can use the one in the SI for PET.

Best,
Gil

**Comment by rmera** [comment]
Hey!

I added a figure of the  Beads.pdb colored by b-factor.
I'm OK with changing it for any other figure, though.

**Comment by rmera** [comment]
That's definitely a good point. I have to see if I have suitable terms (terms where I can clearly show the use of these options), though. Otherwise we could look for a molecule and make a second tutorial that skips over other things and focuses on that. I will look at the data and report back.

**Comment by GilbertoPPereira** [comment]
I added the text in the wiki describing some options. While it does not have the figures there, which I think would be quite useful, at least here are some warnings of things that may occur and how to fix them.

**Comment by rmera** [comment]
Hey Gil,

Where did you add it?

I have been thinking of it. The current example has a pretty short trajectory (so the user can run the whole thing on a laptop). Maybe it would be good to just make another example/tutorial just for those options with a different system and a pre-made trajectory that the user downloads from here (or from somewhere else, if the file is too large)?

**Comment by GilbertoPPereira** [comment]
One option is to grab, for example, Thyroxine, and add the trajectories in zenodo. Then link the zenodo on the tutorial page. I need to check which ligands used some of those options, but that is for sure a good idea.
