### ISSUE TITLE
Remove setting of OMP environment variables in bartender_config.sh

### ISSUE THREAD

**Issue by lgruenewald** [Martini-Force-Field-Initiative/Bartender#13]
Hi guys,
I recently had problems with running xtb and noticed that OMP environment variables are set in the bartender_config.sh. 
The setting of those variables in bartender_config.sh is bad practice and they should be removed. 
Reasons:
1) At no point in the installation description it is mentioned that these variables are set.
2) Setting these variables in secret and hard-coding them results in loss of performance. Most systems have more than two cores. 
3) Since it is not clear that these environment variables are set, it can mess with the normal use of xtb outside of Bartender. 
4) It results in Gromacs errors. Gromacs cannot be run as usual, when the variables are set. 
5) Connected to point 2), running Bartender on a cluster is not efficient and the user may not even notice that xtb is only using 2 cores. 
6) The user has to manually unset the environment variables and will probably not know that they have been set by bartender. This can lead to frustration as usual ways of removing these variables, i.e. starting a new terminal, will not solve the problem.

**Comment by rmera** [comment]
Hey!

I agree, that is something thought for laptops, which is likely not the common setting anymore, so, yeah, a bad default.  In my defense, t he instructions (the INSTALL file) do ask the user to read and modify the  bartender_config.sh script, so I wouldn't say the variable is set in secret.

I'll fix it soon and close the issue when I have.

Thanks!
