### ISSUE TITLE
Can bartender run on apple silicon

### ISSUE THREAD

**Issue by hliu56** [Martini-Force-Field-Initiative/Bartender#14]
Hi

I tried to run a command: bartender  Geometry.xyz BartenderInput.inp, but it will give me the error: zsh: exec format error: bartender

So, I wonder if it can run it on apple silicon with the arm64 architecture?

**Comment by rmera** [comment]
Hi,

It should be possible to compile -most of- Bartender for Mac/arm64. Except maybe for the xtc-format reading feature (which is implemented in an external library, in  C) Bartender is written in pure Go, and so should compile for common architectures.

However, we have only tested building it for x86-64/Linux, and that's also how the binary we ship is compiled (it's the machine/system I have available to test).

So, you could try to compile it for Mac, and I'd expect it to work, but the binary in the release is x86-64/Linux only.

**Comment by hliu56** [comment]
Thanks!

I'll try to compile it for arm64 Mac

At the same time, I tried to install it on a intel-based Mac. When I run `source .bashrc`, it had this error: `-bash: limit: stack size: cannot modify limit: Operation not permitted` (I've tried to use `sudo limit -s unlimited` to reset limit, and it didn't work)

Could you help me see how to cope with it?

**Comment by rmera** [comment]
The binary won't work for Mac on Intel either, as binaries are OS-specific. I would expect the shell script to work, however.  I will ask a Mac user in the team and come back to you.

Something I missed in the last message is that, even if you compile Bartender for your OS/architecture, you'd still need to install [xtb](https://github.com/grimme-lab/xtb/releases/tag/v6.7.1), the QM program used to generate the atomistic trajectories. From what I see in the linked page, they don't provide a Mac binary. They do provide compilation instructions, but I'd expect that to be hard to do.  In addition, the calculations for obtaining the trajectory are quite "expensive" computationally, so it doesn't make much sense to run them on a laptop/desktop computer (except for small molecules).  

A workaround would be to run the trajectories yourself in xtb/Linux/x86-64 and then use Bartender on a Mac laptop to read that trajectory (with the -owntraj flag) and do the rest of the work. In that case, you don't need the "limit -s unlimited" setting (as that setting is for xtb, not for Bartender itself). I personally think it's best to do the whole process on a Linux computing machine, though.

**Comment by hliu56** [comment]
Thank you very much for the explanation!

Indeed, I encountered some errors on xtb after I compiled it on arm64 Mac, see below:
`panic: Failed produce a readable XTB QM-MD trajectory open xtb.trj: no such file or directory
`

I will try to work on a Linux computer. (It would be great if you could create a tutorial for arm64 Mac in the future)

**Comment by hliu56** [comment]
Hi, @rmera 

I've install bartender successfully in linux system, and run a test on my molecules. 
But I encounter a error as below:
'''
Bartender called as:
 bartender DECA.xyz DECA_bartender.inp 

Use:
  $BARTENDERPATH/bartender  [FLAGS] geometry_file input_file
 Use "bartender -help" to see the available flags

panic: runtime error: index out of range [3] with length 3

goroutine 1 [running]:
main.FramePar(0xc00036c038, {0x765608, 0xc0000b0600}, {0xc0000ae300, 0x3, 0x416545?}, 0xc000015770, {0xc00037a018, 0x3, 0x3}, ...)
	/wrk/programs/github.com/rmera/bartender-NB/geos.go:196 +0x113a
main.TrajAn({0x7665c8, 0xc000378030}, {0x765608, 0xc0000b0600}, {0xc0000ae300, 0x3, 0x4}, 0xc000015770, 0x1)
	/wrk/programs/github.com/rmera/bartender-NB/geos.go:92 +0x5ac
main.main()
	/wrk/programs/github.com/rmera/bartender-NB/main.go:243 +0x147a
'''
Could you help me see how to cope with this issue?

Here are the files that i used:
file:///home/schrier2024/Documents/hao/bartender/DECA.zip

**Comment by rmera** [comment]
Hi,

From the error, it seems to me that  there is something wrong with your Bartender input file.  I'd take a look at the documentation for the format, and/or compare with the examples that come with the program.

For me to see the files, you need to upload them somewhere and send me a link.  What you shared is just where they are located in your machine.

**Comment by hliu56** [comment]
Thanks!

I've attached the files here, please let me know if you can access it:
[DECA.zip](https://github.com/user-attachments/files/17873943/DECA.zip)

**Comment by rmera** [comment]
Your inputs seem OK to me. Even weirder,  I'm running Bartender with them right now, and it seems to be running correctly. Did it crash shortly after you ran it, or it took a long time? (i.e. did it crash before or after running the QM-MD simulation?)

**Comment by hliu56** [comment]
Thanks for the checking! Could you tell me how to prepare the `DECA_blank.itp` file. From my understanding, we need to prepare that file by ourselves.

**Comment by ricalessandri** [comment]
This tutorial explains it: https://cgmartini.nl/docs/tutorials/Martini3/Small_Molecule_Parametrization/#on-the-choice-of-bonded-terms-for-the-cg-model; in particular, section 5.1. You can also take a look at similar molecules in the small molecule database (https://github.com/ricalessandri/Martini3-small-molecules/blob/main/LIBRARY.md) or among solvents (https://github.com/marrink-lab/martini-forcefields/blob/main/martini_forcefields/regular/v3.0.0/gmx_files/martini_v3.0.0_solvents_v1.itp).

**Comment by rmera** [comment]
I only checked that the format was correct :S

**Comment by hliu56** [comment]
Thanks for the help! @rmera @ricalessandri 

Another question is: I see the gmx_out.itp file only contain bonds information and the input `.inp, .xyz` files is for information of atom to bead mapping, bonded terms and atomistic structure. 

So, when we prepare the `DECA_blank.itp` as the input of bartender, does the beads type matter for running bartender? (see below image)
e.g. if I only change the beads type, does that change the results of bartender?
<img width="360" alt="image" src="https://github.com/user-attachments/assets/ab4098ba-07aa-450e-a879-59fe5a021817">
