### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by WillPPK** [Martini-Force-Field-Initiative/Bartender#3]
Hi, 

I don't quite understand this part of the instructions..

```
If you are using Bash:

        cd
        echo "export BTROOT=/home/alfred/bartender" >> .bashrc  
        echo "source $BTROOT/packagetools/bartender_config.sh" >> .bashrc
 
If you are using zsh, the last to lines will be:

        echo "export BTROOT=/home/alfred/bartender" >> .zshrc  
        echo "source $BTROOT/packagetools/bartender_config.sh" >> .zshrc
```

which bartender am I supposed to export? I cannot find the file (or executioner) with bartender with lowercase b anywhere..

Thanks!

Will

**Comment by rmera** [comment]
Hey,

I added/fixed information to the README.md.  If you go to https://github.com/Martini-Force-Field-Initiative/Bartender/releases you can download an TGZ file from the last release (v1.0.0-RC2). When you uncompress that (tar xvzf bartender-v1.0.0-RC2-Linux_x86-64-xtc-2024-02-20.15.11.56.tgz)) , you'll find the two binaries inside, bartender (the regular binary, doesn't have any dependency) and bartender-xtc (the xtc-enabled binary, needs the gromacs libraries, which are included in the TGZ file). You'll also find the INSTALL file with instructions, and the shell script bartender_config.sh, which the instructions in INSTALL use to set up shell variables and so on.

I hope this helps.

Cheers,

Raul
