### ISSUE TITLE
Should we have a mailing list?

### ISSUE THREAD

**Issue by rmera** [Martini-Force-Field-Initiative/Bartender#4]
I'm not sure if we just get questions here as issues, or if we should reserve those for actual code problems, and have a mailing list to answer user questions (or some other system, mailing lists are just the familiar thing for me). What do you think?

**Comment by GilbertoPPereira** [comment]
I think that for now, no need to have a mailing list. If we start having a volume of requests/bug fixes/issues opened, then perhaps.

**Comment by ricalessandri** [comment]
In case, we could have a [Discussions](https://docs.github.com/en/discussions) section on Github.

**Comment by rmera** [comment]
Discussions seem better than mailing lists! Should we, or do we wait?

**Comment by lgruenewald** [comment]
I would second a Discussions section

**Comment by ricalessandri** [comment]
I'd wait the opinion of @Lp0lp , but I see no reasons why not to open a Discussions section right away ([here's how to do it](https://docs.github.com/en/discussions/quickstart)).

**Comment by paulocts** [comment]
I think  a Discussions section is good idea. I guess @Lp0lp  and @GilbertoPPereira think the same.

**Comment by ricalessandri** [comment]
OK, great, I see that [Bartender Discussions is live](https://github.com/Martini-Force-Field-Initiative/Bartender/discussions).
I thought there'd be some welcome message ([like this one](https://github.com/marrink-lab/vermouth-martinize/discussions/463)) by default, but I don't see it.

**Comment by Lp0lp** [comment]
Discussions is definitely the best way of doing it!

**Comment by rmera** [comment]
OK then, I'll attempt to set one up, as soon as I finish dealing with a bug I found.
