### ISSUE TITLE
Flags print help all the time.

### ISSUE THREAD

**Issue by WillPPK** [Martini-Force-Field-Initiative/Bartender#7]
When I put any flags in front of the command, the script ended up printing all the help options instead of working around it. (I usually put -v so I know what's going on. Any solutions?

**Comment by rmera** [comment]
Hey!

Bartender will do that when a flag is misused, or a non-existent flag is given. In this case, the -v flag requires a number, i.e. the level of verbosity. Try 2, for instance. I see now that this behavior can be confusing. I'll make sure to clarify it in the Wiki, and consider a change in the flag behavior for a future version.

**Comment by WillPPK** [comment]
Thanks!
